export type iRestBXBizprocWorkflowTemplateFieldEnum =
  'ID'
  | 'MODULE_ID'
  | 'ENTITY'
  | 'DOCUMENT_TYPE'
  | 'AUTO_EXECUTE'
  | 'NAME'
  | 'TEMPLATE'
  | 'PARAMETERS'
  | 'VARIABLES'
  | 'CONSTANTS'
  | 'MODIFIED'
  | 'IS_MODIFIED'
  | 'USER_ID'
  | 'SYSTEM_CODE'
